# Generated by Django 4.2 on 2023-04-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_commentsmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsmodel',
            name='email',
        ),
    ]
