# Generated by Django 4.2 on 2023-05-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizegridmodel',
            options={'ordering': ('name',)},
        ),
    ]
