# Generated by Django 4.2 on 2023-05-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_productmodel_size_productmodel_sizes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='count',
        ),
        migrations.AlterField(
            model_name='productsizemodel',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
