# Generated by Django 4.2 on 2023-05-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_productmodel_category_productmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproductmodel',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='sizegridmodel',
            name='name',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
