# Generated by Django 4.2 on 2023-06-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_checkoutmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('discount', models.PositiveSmallIntegerField(default=0)),
                ('date_expirations', models.DateTimeField()),
            ],
        ),
    ]
