# Generated by Django 4.2 on 2023-06-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_couponcodemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcodemodel',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
