# Generated by Django 4.2 on 2023-05-13 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1500)),
                ('development', models.CharField(max_length=200)),
                ('design', models.CharField(max_length=200)),
                ('photography', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/image')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='portfolio/image')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='portfolio/image')),
                ('video', models.FileField(blank=True, null=True, upload_to='portfolio/video')),
                ('client', models.CharField(max_length=150)),
                ('date_create', models.DateField(auto_now=True)),
                ('link_on_project', models.URLField(blank=True, max_length=128, null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
