# Generated by Django 4.2 on 2023-05-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_commentsmodel_email'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='category',
            field=models.ManyToManyField(to='blog.categorymodel'),
        ),
    ]
