# Generated by Django 4.2 on 2023-05-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliomodel_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliomodel',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='date_create',
            field=models.DateField(),
        ),
    ]
