# Generated by Django 4.2 on 2023-05-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_categorymodel_slug'),
        ('portfolio', '0004_alter_portfoliomodel_link_on_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category',
            field=models.ManyToManyField(related_name='cat', to='blog.categorymodel'),
        ),
    ]
