# Generated by Django 4.2 on 2023-05-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_categorymodel_slug'),
        ('portfolio', '0005_alter_portfoliomodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category',
            field=models.ManyToManyField(to='blog.categorymodel'),
        ),
    ]
